name: Linux_Container_Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Login via Docker'
          uses: azure/docker-login@v1
          with:
            login-server: avwxrest.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        
        - name: 'Build and Push Container'
          run: |
            docker build . -t avwxrest.azurecr.io/avwx-account-dev:${{ github.sha }}
            docker push avwxrest.azurecr.io/avwx-account-dev:${{ github.sha }}
