name: Nox

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Nox
        uses: excitedleigh/setup-nox@v2.1.0
      - name: Run Nox
        env:
          MAIL_CONSOLE: true
          MONGO_URI: none
          SALT: ${{ secrets.SALT }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          TEST_MONGO_URI: ${{ secrets.TEST_MONGO_URI }}
          MC_KEY: ${{ secrets.MC_KEY }}
          MC_USERNAME: ${{ secrets.MC_USERNAME }}
        run: nox
